-- 導師檔案欄位 + email/密碼改為可選
ALTER TABLE "User" ALTER COLUMN "email" DROP NOT NULL;
ALTER TABLE "User" ALTER COLUMN "passwordHash" DROP NOT NULL;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "tutorNo" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "region" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "subjects" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "scrcExpiry" DATE;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dseResult" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "education" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "experience" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "remarks" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dob" DATE;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hkid" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "payeeName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bankCode" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bankAccount" TEXT;
